Importing all dependencies

In [31]:
import pandas as pd

In [32]:
import numpy as np

In [33]:
import matplotlib.pyplot as plt

In [34]:
import seaborn as sns

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [38]:
df=pd.read_csv("spam.csv",encoding="latin1")

In [39]:
df

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [40]:
df = df.drop(columns=["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])

In [41]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

Replacing the missing or the null value eith a string

In [42]:
raw_data=df.where((pd.notnull(df)),'')

In [43]:
raw_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
#chech the number of rows and columns in a dataframe
raw_data.shape

(5572, 2)

In [70]:
raw_data['Category'] = raw_data['Category'].astype(object)
raw_data.loc[raw_data['Category'] == 'spam', 'Category'] = 0
raw_data.loc[raw_data['Category'] == 'ham', 'Category'] = 1

Spam=0
Ham=1

In [71]:
#seprating data as text and labels
X=raw_data['Message']
Y=raw_data['Category']

In [72]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: str

In [73]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [74]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

In [76]:
X_train.shape

(4457,)

In [81]:
X_test.shape

(1115,)

In [83]:
#Transform the text to feature vectors that can be used as input to logistic regression
feature_extraction=TfidfVectorizer(min_df,stop_words,lowercase='True')
X_train_features=feature_extraction.fit_transform(X_train))
X_test_features=feature_extraction.fit_transform(X_test)

#convert Y_train and Y_test values into integer
Y_train=Y_train.astype('int')
Y_test=Y_test.astype('int')

SyntaxError: unmatched ')' (738208650.py, line 3)